### ISSUE TITLE
How to enable/get the EXPORT button from the version 0.3.2?

### ISSUE THREAD

**Issue by javierorozco** [quantopian/qgrid#141]
How to enable/get the EXPORT button from the version 0.3.2? This is not visible in the 1.0 version!

**Comment by TimShawver** [comment]
The export button is gone in qgrid 1.0 and it's no longer possible to export a fully functional version of qgrid to static html, because in the new version of qgrid the sorting/filtering logic is done on the server (so I'd have to reproduce that logic in javascript). Also, there is an issue in nbconvert which prevents exporting widgets from working with ipywidgets 7 (which qgrid 1.0 depends on), so exporting a partially functional version is not currently possible either.  

Exporting a partially functional version of qgrid where sorting/filtering is broken (and only 200 rows are included) WILL be possible once https://github.com/jupyter/nbconvert/issues/636 is fixed. When that issue is fixed, that would be done with the following steps:

![screen shot 2017-11-08 at 11 31 48 am](https://user-images.githubusercontent.com/5055866/32560764-7a967378-c478-11e7-9d14-c1a45e25f686.png)

![screen shot 2017-11-08 at 11 24 29 am](https://user-images.githubusercontent.com/5055866/32560622-1cad50d8-c478-11e7-8f85-05e73cb362cb.png)

I realize a partially functional version of the grid with only 200 rows is probably not all that useful to people so another alternative that might be a better option is to use the new "binder" service for rendering live notebooks. I'm using it to host the demo notebook for qgrid and it's been great so far: https://beta.mybinder.org/v2/gh/quantopian/qgrid-notebooks/master?filepath=index.ipynb

If lots of people complain about the needing a fully functional static html export of the qgrid, I'll look into doing that once the nbconvert bug is fixed that's blocking exporting from working with ipywidgets 7.

**Comment by javierorozco** [comment]
@TimShawver Thank you for the information, I will keep up on track when the fix is deployed.
Cheers!

**Comment by ar-siddiqui** [comment]
@TimShawver looks like the nbconvert fix have been deployed but I still can't see qgrids in HTML export after following the steps you mentioned.
