### ISSUE TITLE
Not compatible with JupyterLab 1.0

### ISSUE THREAD

**Issue by qzchenwl** [quantopian/qgrid#261]
After upgrade JupyterLab to 1.0.2, qgrid-1.1.1 plugin failed to load.
![image](https://user-images.githubusercontent.com/146802/61169396-523ac380-a58f-11e9-831d-9cc7cd7ef3eb.png)

**Comment by LukaPitamic** [comment]
yup, same here. I can't live without it!!! Please make it compatible.

**Comment by DentonGentry** [comment]
I've been trying to install a dev version locally, applying the patch in https://github.com/quantopian/qgrid/pull/262/commits/58eb09c38ff8bda653b6b88be6bf95df8d128fed, but during the "jupyter labextension install" npm is outsmarting me. npm always fetches qgrid 1.1.1 and I haven't figured out how to make it use the development qgrid I've installed locally.

**Comment by 0xmjk** [comment]
Try running the following
```
  pip install --no-cache-dir .
  jupyter labextension install js/
```
Hope it helps!

**Comment by ankostis** [comment]
I'm still getting an error:
```bash
qgrid-dev.git$ jupyter labextension install js/
Building jupyterlab assets
The extension "@jupyter-widgets/jupyterlab-manager" is outdated.

grid-dev.git$ git lg
* 58eb09c - (8 days ago) adapt to jupyterlab 1.0.2 - chenwenlong02 (grafted, HEAD -> master, origin/master, origin/HEAD)

grid-dev.git$ pip list | grep -iE 'jupyter|ipython'
ipython                            7.5.0      
ipython-genutils                   0.2.0      
jupyter-client                     5.2.4      
jupyter-core                       4.4.0      
jupyterlab                         1.0.2      
jupyterlab-server                  1.0.0    
```

Any ideas why?

**Comment by 0xmjk** [comment]
I run
```sh
jupyter labextension install @jupyter-widgets/jupyterlab-manager
```
after installing jupyterlab with:
```
pip3 install --no-cache-dir --upgrade https://github.com/jupyterlab/jupyterlab/archive/v1.0.2.tar.gz 
jupyter serverextension enable --py jupyterlab
```
and it works...

Pip list returns:
```
$ pip list | grep -iE "jupyter|ipython"
ipython                7.6.1
ipython-genutils       0.2.0
jupyter-client         5.3.1
jupyter-core           4.5.0
jupyterlab             1.0.2
jupyterlab-server      1.0.0
```

**Comment by ankostis** [comment]
Thank you.  It worked after repeating all jupyterlab & qgrid installation steps.

**Comment by 0xmjk** [comment]
Great! You're welcome! 😄

**Comment by amsimms** [comment]
There seems to be some missing installation/initialization that always bites me when attempting to install qgrid in a new location.  I will note that I'm installing using conda. 

The problem usually boils down to this error:

qgrid.show_grid(df)
**Error displaying widget: model not found**

And the only clues are in the JavaScript console (I'm running Chrome):

Uncaught (in promise) Error: Module qgrid, semver range 1.1.1 is not registered as a widget module
    at WidgetManager.loadClass (vendors~main.14a84808aa28d72e84ae.js:442885)
    at WidgetManager.<anonymous> (vendors~main.14a84808aa28d72e84ae.js:494136)
    at step (vendors~main.14a84808aa28d72e84ae.js:493917)
    at Object.next (vendors~main.14a84808aa28d72e84ae.js:493898)
    at vendors~main.14a84808aa28d72e84ae.js:493892
    at new Promise (<anonymous>)
    at push.hs2k.__awaiter (vendors~main.14a84808aa28d72e84ae.js:493888)
    at WidgetManager.push.hs2k.ManagerBase._make_model (vendors~main.14a84808aa28d72e84ae.js:494130)
    at WidgetManager.<anonymous> (vendors~main.14a84808aa28d72e84ae.js:494119)
    at step (vendors~main.14a84808aa28d72e84ae.js:493917)

jupyter-labextension  list
JupyterLab v1.0.2
Known labextensions:
   app dir: /Users/asimms/anaconda3/envs/drclab/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v1.0.1  enabled  OK
        @jupyterlab/plotly-extension v0.18.2  enabled  OK
        qgrid v1.1.1  enabled  OK

Most times repeatedly issuing the install commands listed above seems to magically fix it, but no luck today.

**Comment by marcociccone** [comment]
same issue here!

**Comment by 0xmjk** [comment]
It looks like you get qgrid extension from the original one rather than the patched version.

My labextension list shows (after running `jupyter labextension install js/`, of course):
```
   local extensions:
        qgrid: /usr/src/qgrid/js
```
which is not ideal, but as I'm running it in a container anyway I don't care.

**Comment by amsimms** [comment]
This has been several days--is qgrid going to be fixed or is this project no longer active?

**Comment by LukaPitamic** [comment]
yup, I'm also waiting for the JupyterLab 1.x support. For now I'm helping myself with [ipysheet](https://github.com/QuantStack/ipysheet). Patiently waiting for QGrid to become compatible officially...

**Comment by DentonGentry** [comment]
A comment by @gmanoim-quantopian 9 days ago on https://github.com/quantopian/qgrid/pull/262#discussion_r311132890 suggested a change to the pull request originally sent by @qzchenwl.

**Comment by ankostis** [comment]
@0xmjk with jupytlab-1.1.0 i'm still getting the chrome-console error that @amsimms mentioned above:

```
Uncaught (in promise) Error: Module qgrid, semver range 1.1.1 is not registered as a widget module
    at x.loadClass (manager.js:251)
    at x.<anonymous> (manager-base.js:263)
    at l (manager-base.js:44)
    at Object.next (manager-base.js:25)
    at manager-base.js:19
```

When running `jupyter labextension list`, qgrid is listed under both the "app dir:" and in "local extensions:' lists.  

```
JupyterLab v1.1.0
Known labextensions:
   app dir: /home/ankostis/Work/wltp.git/venv/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v1.0.2  enabled  OK
        @jupyterlab/celltags v0.1.5  enabled  OK
        jupyter-matplotlib v0.4.2  enabled  OK
        jupyterlab-jupytext v1.0.2  enabled  OK
        qgrid v1.1.1  enabled  OK*

   local extensions:
        qgrid: /home/user/qgrid-dev.git/js
```
Is this expected?

My env:
```
$ pip list | grep -iE "jupyter|ipython|note"
ipython                            7.7.0       
ipython-genutils                   0.2.0       
jupyter                            1.0.0       
jupyter-client                     5.3.1       
jupyter-console                    6.0.0       
jupyter-core                       4.5.0       
jupyterlab                         1.1.0       
jupyterlab-server                  1.0.6       
notebook                           6.0.1 
```

Any ideas how to install qgrd?

**Comment by ankostis** [comment]
Followed @kafka-tamura instructions  (in his fork) of installing and rebuilding before re-installing qgrid, and still this extension does not work.

**Comment by kafka-tamura** [comment]
@ankostis There was a problem with instructions. Can you try again with new instructions?

**Comment by ankostis** [comment]
I had already tried roughly your edits, and still i m getting the same `Module qgrid, semver range 1.1.1 is not registered` error on chrome-console@linux.

Can you paste here your versions?
```bash
$ pip list | grep -iE "jupy|ipython|note|qgrid|matplo|ipy"
ipykernel                          5.1.2       
ipympl                             0.3.3       
ipython                            7.7.0       
ipython-genutils                   0.2.0       
ipywidgets                         7.5.1       
jupyter                            1.0.0       
jupyter-client                     5.3.1       
jupyter-console                    6.0.0       
jupyter-core                       4.5.0       
jupyterlab                         1.1.0       
jupyterlab-server                  1.0.6       
jupytext                           1.2.1       
matplotlib                         3.1.1       
notebook                           6.0.1       
qgrid                              1.1.1       /home/user/qgrid-dev.git
scipy                              1.3.1       

$ jupyter labextension list
JupyterLab v1.1.0
Known labextensions:
   app dir: /home/ankostis/Work/wltp.git/venv/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v1.0.2  enabled  OK
        jupyter-matplotlib v0.4.2  enabled  OK
        jupyterlab-jupytext v1.0.2  enabled  OK
        qgrid v1.1.1  enabled  OK*

   local extensions:
        qgrid: /home/user/qgrid-dev.git/
```

**Comment by ankostis** [comment]
I managed  to make the latest `jupyterlab-1.1.0` + `qgrid` work in binder (https://github.com/JRCSTU/wltp), but still it does not work on my PC :-/.

@kafka-tamura, i realized that it is not even necessary to install in *develop mode*! 
Pip-installing the existing *qgrid* from PyPi will do, as long as you then install the patched javascript code here with `jupyter labextension install qgrid.git/js`.
.

**Comment by kafka-tamura** [comment]
@ankostis Thanks. That is quite surprising. I couldn't get it to work with my `pip` installed `qgrid` - so had to install `qgrid` in develop mode.

**Comment by ankostis** [comment]
@kafka-tamura  well, i was surprised to.  
But if you look at the diffs of the PR, it has changes only on the javascript side.

**Comment by ankostis** [comment]
For the record, I made my PC to work with the patched PR.  Used the "shortcut", installing from PyPi and installing JS from the PR only.
Unfortunately I don't know why it didn't work before....

**Comment by yhavinga** [comment]
Hi all,
The info in this thread (thanks!) solved my "Loading widget..." problem, that I got after upgrade from an older jupyter and jupyterlab to the latest lab and notebook versions.
The following commands worked for me:

```
# first uninstall a previously installed qgrid package
git clone https://github.com/quantopian/qgrid
cd qgrid/
git checkout 6d99d34574c7ea25c129058e834e04c489da2976
pip install --no-cache-dir .
jupyter labextension install js/
jupyter-labextension list
```
This will install qgrid patched to 1.2.0, per the pull request linked to at the beginning of this thread.
The output of `jupyter-labextension list`:
```
JupyterLab v1.1.4
Known labextensions:

   local extensions:
        qgrid: /home/jovyan/qgrid/js
   app dir: /opt/conda/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v1.0.2  enabled  OK
        jupyterlab_bokeh v1.0.0  enabled  OK
        qgrid v1.1.1  enabled  OK*
```
other versions `pip list | grep -iE "qgrid|jupy|notebook" `
```
jupyter-client                    5.3.3    
jupyter-contrib-core              0.3.3    
jupyter-contrib-nbextensions      0.5.1    
jupyter-core                      4.4.0    
jupyter-highlight-selected-word   0.2.0    
jupyter-latex-envs                1.4.4    
jupyter-nbextensions-configurator 0.4.1    
jupyterhub                        1.0.0    
jupyterlab                        1.1.4    
jupyterlab-server                 1.0.6    
notebook                          6.0.0    
qgrid                             1.2.0   
```

**Comment by ankostis** [comment]
@yhavinga it should have worked even if you pip intalled normally (from PyPi) and only install the javascript lab-extensions from the cloned repo.

**Comment by konradsitarz** [comment]
> Hi all,
> The info in this thread (thanks!) solved my "Loading widget..." problem, that I got after upgrade from an older jupyter and jupyterlab to the latest lab and notebook versions.
> The following commands worked for me:
> 
> ```
> # first uninstall a previously installed qgrid package
> git clone https://github.com/quantopian/qgrid
> cd qgrid/
> git checkout 6d99d34574c7ea25c129058e834e04c489da2976
> pip install --no-cache-dir .
> jupyter labextension install js/
> jupyter-labextension list
> ```
> 
> This will install qgrid patched to 1.2.0, per the pull request linked to at the beginning of this thread.
> The output of `jupyter-labextension list`:
> 
> ```
> JupyterLab v1.1.4
> Known labextensions:
> 
>    local extensions:
>         qgrid: /home/jovyan/qgrid/js
>    app dir: /opt/conda/share/jupyter/lab
>         @jupyter-widgets/jupyterlab-manager v1.0.2  enabled  OK
>         jupyterlab_bokeh v1.0.0  enabled  OK
>         qgrid v1.1.1  enabled  OK*
> ```
> 
> other versions `pip list | grep -iE "qgrid|jupy|notebook" `
> 
> ```
> jupyter-client                    5.3.3    
> jupyter-contrib-core              0.3.3    
> jupyter-contrib-nbextensions      0.5.1    
> jupyter-core                      4.4.0    
> jupyter-highlight-selected-word   0.2.0    
> jupyter-latex-envs                1.4.4    
> jupyter-nbextensions-configurator 0.4.1    
> jupyterhub                        1.0.0    
> jupyterlab                        1.1.4    
> jupyterlab-server                 1.0.6    
> notebook                          6.0.0    
> qgrid                             1.2.0   
> ```
It worked for me. 

```
JupyterLab v1.1.4
Known labextensions:
   app dir: /home/konrad/Documents/wya-analytics/venv/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v1.0.2  enabled  OK
        jupyterlab-plotly v1.1.0  enabled  OK
        plotlywidget v1.1.0  enabled  OK
        qgrid v1.1.1  enabled  OK*

   local extensions:
        qgrid: /home/konrad/Documents/qgrid.git/js
```

**Comment by LukaPitamic** [comment]
Hi Guys, am I understanding this thread right - QGrid still is NOT working with JLab v1? I was using it regularly and loved it, but the lack of maintenance (clearly shown by not catching up with JLab amazing development trajectory) kind of indicates to problems and challenges in the future. Again it is a wonderful, wonderful tool, but we were forced to migrate to [Ipysheet](https://github.com/QuantStack/ipysheet). I wish QGrid though.

**Comment by ankostis** [comment]
TO: @ehebert @ernestoeperez88 @fawce @irlevesque @jbredeche @jdricklefs @llllllllll @richafrank @ssanderson ssanderson

Is anybody watching this repo?
Do you need help to bake a new release for Lab v?

**Comment by LukaPitamic** [comment]
@ankostis WTG!!!!

**Comment by tkrabel** [comment]
I have seen that @qzchenwl has created an npm package. However, it's not working on my system. That's why I have created my own npm package.

For those of you who want to install the qgrid JS in the usual way and not from a github repo directly, you can do it now the following way:

    jupyter labextension @8080labs/qgrid

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/tkrabel/qgrid_jupyterlab/master?urlpath=lab/tree/qgrid_demo.ipynb)

You can find a binder demo repo here: [https://github.com/tkrabel/qgrid_jupyterlab](https://github.com/tkrabel/qgrid_jupyterlab)

**Comment by gerrymanoim** [comment]
Fixed in https://github.com/quantopian/qgrid/pull/275

**Comment by prncevince** [comment]
@gerrymanoim this is still an issue. 

Same `semver range 1.1.1 is not registered as a widget model` error mentioned above.
However, I'm up to JupyterLab 1.2.4. Will this consistently be an issue with upgrades?

```
➜  pip list | grep -iE 'jupyter|ipython|qgrid' 
ipython                            7.11.1             
ipython-genutils                   0.2.0              
jupyter                            1.0.0              
jupyter-client                     5.3.4              
jupyter-console                    5.2.0              
jupyter-core                       4.6.1              
jupyterlab                         1.2.4              
jupyterlab-server                  1.0.6              
qgrid                              1.2.0 
``` 
<img width="433" alt="modelNotFound" src="https://user-images.githubusercontent.com/17718313/72196440-12da1c00-33e6-11ea-8703-f8bb42429f6d.png">

<img width="505" alt="semverrangenotregistered" src="https://user-images.githubusercontent.com/17718313/72196430-0eadfe80-33e6-11ea-81c2-ba036bca27ec.png">

**Comment by prncevince** [comment]
I also have a hunch that this is an underlying JupyterLab extension issue. The `semver range is not registered error` is everywhere, and I cannot find a good troubleshooting guide to fix it ...

**Comment by tkrabel** [comment]
@prncevince how did you install the qgrid JS extension? I saw that the new qgrid JS extension hasn't been published to npm yet, so if you type `jupyter labextension install qgrid`, you still have the non-working version. You still would have to clone the github repo and install the JS files locally, or you can install my version of the JS extension that has that fix in it.

**Comment by prncevince** [comment]
@gerrymanoim @tkrabel thanks! The local install fixes things. 

Also, for what it's worth, and idk if its best practice, but you can get rid of  `local extensions: ...` from `jupyter labextension list` by directly deleting them from the jupyter lab app directory's `build_config.json` file (e.g. `~/anaconda3/share/jupyter/lab/settings/build_config.json`).

I also removed the qgrid item in `"linkedPackages"` from `.../jupyter/lab/staging/package.json`, rebuilt with `jupyter lab build` & now it's as if qgrid is a regularly installed lab extension I suppose.

**Comment by Nestak2** [comment]
@tkrabel @ankostis Since the issue persists for some users, as mentioned in #286, would you mind listing the installation commands for all the necessary packages that make qgrid's newest version work for you? I have tried your recommendations from the last weeks and months on a few fresh conda environments and nothing works for me. 

@prncevince Can you elaborate on what fixed the issue for you? How do I do the "local install" (of JS I guess?)?

**Comment by prncevince** [comment]
@Nestak2 as stated in the [JupyterLab Developer docs](https://jupyterlab.readthedocs.io/en/stable/developer/extension_dev.html#extension-authoring), a labextension is an NPM package. 

This issue thread essentially explains that the [qgrid package on npm registry](https://www.npmjs.com/package/qgrid), hasn't been updated to the updated code found within https://github.com/quantopian/qgrid/tree/master/js (where the updated package resides).

The extension install command `jupyter labextension install qgrid` will install qgrid from npm (currently, the old version).

@tkrabel's fix contains the updated package, so `jupyter labextension install @8080labs/qgrid`, should grab his package at https://www.npmjs.com/package/@8080labs/qgrid, which will allow you to perform the native JupyterLab user install command. The extension should then work in JupyterLab as long as you have the qgrid python package installed too, i.e. via `pip install qgrid`.

What I did was a little different. I installed the extension locally via:

```
git clone https://github.com/quantopian/qgrid.git
jupyter labextension install qgrid.git/js
```

This way, you'll have a leftover local git repo, which you can then delete.

**Comment by Nestak2** [comment]
@prncevince Thanks for the extensive answer. I retried your suggestions in a new conda environment just to be sure, the complete list of installations looks like that:
```
# the first 4 lines just create an environment and a kernel
conda create -n env_qgr3 python=3.7
source activate env_qgr3
conda install ipykernel
python -m ipykernel install --user --name env_qgr3 --display-name "env_qgr3"

conda config --add channels conda-forge
conda install jupyterlab
conda install qgrid
git clone https://github.com/quantopian/qgrid.git
conda install nodejs
jupyter labextension install qgrid.git/js
jupyter nbextension enable --py --sys-prefix widgetsnbextension
```

Unfortunately, this still doesn't enable qgird, I only get as output below the cell "Loading widget...". My list of packages and extensions is:

```
$ conda list | grep -iE "jupy|ipython|note|qgrid|matplo|ipy|js"
ipykernel                 5.1.3            py37h5ca1d4c_0    conda-forge
ipympl                    0.4.1                      py_0    conda-forge
ipython                   7.11.1           py37h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1                      py_0    conda-forge
json5                     0.8.5                      py_0    conda-forge
jsonschema                3.2.0                    py37_0    conda-forge
jupyter_client            5.3.4                    py37_1    conda-forge
jupyter_core              4.6.1                    py37_0    conda-forge
jupyterlab                1.2.6                      py_0    conda-forge
jupyterlab_server         1.0.6                      py_0    conda-forge
matplotlib-base           3.1.2            py37h250f245_1    conda-forge
nodejs                    13.7.0               h10a4023_0    conda-forge
notebook                  6.0.3                    py37_0    conda-forge
qgrid                     1.1.1                 py37_1001    conda-forge

$ jupyter labextension list
JupyterLab v1.2.6
Known labextensions:
   app dir: /home/nestor/anaconda3/envs/env_qgr2/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v1.1.0  enabled  OK
        jupyter-matplotlib v0.5.0  enabled  OK
        qgrid v1.1.1  enabled  OK*

   local extensions:
        qgrid: /home/nestor/qgrid.git/js
```
 Do you spot a problem in my environment?

**Comment by prncevince** [comment]
Your JupyterLab version is `1.2.6`. I believe [version `1.2.0`](https://github.com/quantopian/qgrid/releases/tag/v1.2.0) of the Qgrid Python package fixes compatibility for JupyterLab > 1.0.0, that was the reason for merge  #275 

So I think that you need `1.2.0` of the QGrid Python package (you have `1.1.1`). It's available on conda So I would do a:

`pip install -U qgrid`

**Comment by prncevince** [comment]
Also, you will probably need to install pip to the new environment since you're working with a fresh conda environment, so I would do `conda install pip` 1st. Otherwise, pip will install to your `base` env.

**Comment by Nestak2** [comment]
@prncevince Thanks, problem fixed! It works now with with `jupyterlab v=1.2.4` and `qgrid v=1.2.0`. Strangely enough, qgrid started working also in my other conda environments where I have other versions of jupyterlab and qgrid and where qgrid wasn't working before. Maybe the fix is also due to a jupyterlab pop-up window that appeared after creating my latest environment saying:

```
Build Recommended
JupyterLab build is suggested:
@jupyter-widgets/jupyterlab-manager needs to be included in build
jupyter-matplotlib needs to be included in build
qgrid needs to be included in build 
```
I clicked on the button "build" and then qgrid started working in all environments.

My installations steps in the latest conda environment are:

```
# the first 4 lines just create an environment and a kernel
conda create -n env_qgr python=3.7
source activate env_qgr
conda install ipykernel
python -m ipykernel install --user --name env_qgr --display-name "env_qgr"

conda config --add channels conda-forge
conda install jupyterlab=1.2.4
conda install pip
pip install -U qgrid
git clone https://github.com/quantopian/qgrid.git
conda install nodejs
jupyter labextension install qgrid.git/js
jupyter nbextension enable --py --sys-prefix widgetsnbextension
```
(Then, when I first opened jupyterlab I had the pop-up window "Build Recommended")

My package versions:
```
$ conda list | grep -iE "jupy|ipython|note|qgrid|matplo|ipy|js"
ipykernel                 5.1.3            py37h5ca1d4c_0    conda-forge
ipython                   7.11.1           py37h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1                    pypi_0    pypi
json5                     0.8.5                      py_0    conda-forge
jsonschema                3.2.0                    py37_0    conda-forge
jupyter_client            5.3.4                    py37_1    conda-forge
jupyter_core              4.6.1                    py37_0    conda-forge
jupyterlab                1.2.4                      py_0    conda-forge
jupyterlab_server         1.0.6                      py_0    conda-forge
nodejs                    13.7.0               h10a4023_0    conda-forge
notebook                  6.0.3                    py37_0    conda-forge
qgrid                     1.2.0                    pypi_0    pypi

$ jupyter labextension list
JupyterLab v1.2.4
Known labextensions:
   app dir: /home/nestor/anaconda3/envs/env_qgr4/share/jupyter/lab
        qgrid v1.1.1  enabled  OK*

   local extensions:
        qgrid: /home/nestor/qgrid.git/js

```

**Comment by ankostis** [comment]
There is a new QGrid "fork" (the same codebase just not git-cloned) that works with all latest jupyter machinery, minus `ipywidgets-8+`:

https://github.com/JohnOmernik/qgrid

It was packaged with all NPM dependencies in wheels, and works out of the box.
