### ISSUE TITLE
pandas DataFrame containing columns with datetime dtype doesn't display with qgrid 1.3.1 in JupyterLab 2.1.2

### ISSUE THREAD

**Issue by lebedov** [quantopian/qgrid#317]
### Environment

* Operating System: Ubuntu 18.04.4
* Python Version: Python 3.7.6
* How did you install Qgrid: pip
* Python packages: 
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                      1_llvm    conda-forge
attrs                     19.3.0                     py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
bleach                    3.1.5              pyh9f0ad1d_0    conda-forge
brotlipy                  0.7.0           py37h8f50634_1000    conda-forge
ca-certificates           2020.4.5.1           hecc5488_0    conda-forge
certifi                   2020.4.5.1       py37hc8dfbb8_0    conda-forge
cffi                      1.14.0           py37hd463f26_0    conda-forge
chardet                   3.0.4           py37hc8dfbb8_1006    conda-forge
cryptography              2.9.2            py37hb09aad4_0    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
entrypoints               0.3             py37hc8dfbb8_1001    conda-forge
icu                       67.1                 he1b5a44_0    conda-forge
idna                      2.9                        py_1    conda-forge
importlib-metadata        1.6.0            py37hc8dfbb8_0    conda-forge
importlib_metadata        1.6.0                         0    conda-forge
ipykernel                 5.2.1            py37h43977f1_0    conda-forge
ipython                   7.14.0           py37hc8dfbb8_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1                    pypi_0    pypi
jedi                      0.17.0           py37hc8dfbb8_0    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
json5                     0.9.0                      py_0    conda-forge
jsonschema                3.2.0            py37hc8dfbb8_1    conda-forge
jupyter_client            6.1.3                      py_0    conda-forge
jupyter_core              4.6.3            py37hc8dfbb8_1    conda-forge
jupyterlab                2.1.2                      py_0    conda-forge
jupyterlab_server         1.1.3                      py_0    conda-forge
ld_impl_linux-64          2.34                 h53a641e_0    conda-forge
libblas                   3.8.0               16_openblas    conda-forge
libcblas                  3.8.0               16_openblas    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgfortran-ng            7.3.0                hdf63c60_5    conda-forge
liblapack                 3.8.0               16_openblas    conda-forge
libopenblas               0.3.9                h5ec1e0e_0    conda-forge
libsodium                 1.0.17               h516909a_0    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
libuv                     1.34.0               h516909a_0    conda-forge
llvm-openmp               10.0.0               hc9558a2_0    conda-forge
markupsafe                1.1.1            py37h8f50634_1    conda-forge
mistune                   0.8.4           py37h8f50634_1001    conda-forge
nbconvert                 5.6.1            py37hc8dfbb8_1    conda-forge
nbformat                  5.0.6                      py_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
nodejs                    14.2.0               h568c755_1    conda-forge
notebook                  6.0.3            py37hc8dfbb8_0    conda-forge
numpy                     1.18.4           py37h8960a57_0    conda-forge
openssl                   1.1.1g               h516909a_0    conda-forge
packaging                 20.1                       py_0    conda-forge
pandas                    1.0.3            py37h0da4684_1    conda-forge
pandoc                    2.9.2.1                       0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.7.0              pyh9f0ad1d_0    conda-forge
pexpect                   4.8.0            py37hc8dfbb8_1    conda-forge
pickleshare               0.7.5           py37hc8dfbb8_1001    conda-forge
pip                       20.1               pyh9f0ad1d_0    conda-forge
prometheus_client         0.7.1                      py_0    conda-forge
prompt-toolkit            3.0.5                      py_0    conda-forge
prompt_toolkit            3.0.5                         0    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
pycparser                 2.20                       py_0    conda-forge
pygments                  2.6.1                      py_0    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyrsistent                0.16.0           py37h8f50634_0    conda-forge
pysocks                   1.7.1            py37hc8dfbb8_1    conda-forge
python                    3.7.6           h8356626_5_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
pyzmq                     19.0.1           py37hac76be4_0    conda-forge
qgrid                     1.3.1                    pypi_0    pypi
readline                  8.0                  hf8c457e_0    conda-forge
requests                  2.23.0             pyh8c360ce_2    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                46.1.3           py37hc8dfbb8_0    conda-forge
six                       1.14.0                     py_1    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
terminado                 0.8.3            py37hc8dfbb8_1    conda-forge
testpath                  0.4.4                      py_0    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
tornado                   6.0.4            py37h8f50634_1    conda-forge
traitlets                 4.3.3            py37hc8dfbb8_1    conda-forge
urllib3                   1.25.9                     py_0    conda-forge
wcwidth                   0.1.9              pyh9f0ad1d_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.34.2                     py_1    conda-forge
widgetsnbextension        3.5.1                    pypi_0    pypi
xz                        5.2.5                h516909a_0    conda-forge
zeromq                    4.3.2                he1b5a44_2    conda-forge
zipp                      3.1.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
```
* Jupyter lab packages (if applicable): `$ jupyter labextension list`
```
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        qgrid2 v1.1.3  enabled  OK
```
### Description of Issue

Pandas DataFrames containing columns with datetime dtype are no longer displayed by qgrid in JupyterLab 2.1.2, i.e., nothing appears in the cell output, and no error message is displayed.

### Reproduction Steps

1. After installing JupyterLab 2.1.2, qgrid 1.3.1, and the required JupyterLab extensions, attempt to run the following code in a new notebook:
```python
import datetime
import pandas as pd
import qgrid

df = pd.DataFrame({'a': [datetime.datetime(2020,1,1,10,1), datetime.datetime(2020,1,1,11)]})
qgrid.show_grid(df)
```
2. Nothing will be displayed in the cell output.
3. If the DataFrame is modified to contain a mix of datetime and non-datetime
values, the DataFrame will be displayed normally.
4. Repeat the above with JupyterLab 2.1.0; the qgrid widget will be displayed normally.

### What steps have you taken to resolve this already?

Revert to JupyterLab 2.1.0.

**Comment by jfbeaumont** [comment]
Thank you for posting this. That helped a lot!

With Python 3.7.0, here is what I did to get qgrid to work:

```
pip install qgrid==1.3.1
pip install jupyterlab==2.1.0
jupyter nbextension enable --py --sys-prefix qgrid
jupyter nbextension enable --py --sys-prefix widgetsnbextension
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install qgrid2
jupyter lab build
```

If you don't have nodejs (which is required for "labextension install" and "lab build" commands) on an old system, I found one that worked for me by installing Anaconda3.

**Comment by lebedov** [comment]
The problem seems to have been resolved in JupyterLab 2.1.3.

**Comment by drlelong** [comment]
I'm still getting the "Error displaying widget: model not found" after upgrading to Jupyter 2.1.5.

Here is what I ran:

```
pip install qgrid==1.3.1
pip install jupyterlab==2.1.5
jupyter nbextension enable --py --sys-prefix qgrid
jupyter nbextension enable --py --sys-prefix widgetsnbextension
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install qgrid2
jupyter lab build
```

**Comment by lebedov** [comment]
@drlelong Not sure why it isn't working for you - when I tried running jupyterlab from within a new conda environment created as follows, the widget was displayed properly:

```
conda create -n jupyterlab-2.1.5 jupyterlab=2.1.5
conda activate jupyterlab-2.1.5
conda install qgrid nodejs
jupyter labextension install @jupyter-widgets/jupyterlab-manager qgrid2
jupyter lab build
```

**Comment by drlelong** [comment]
After adjusting my environment to reinstall qgrid from conda (which results in v1.1.1) and reinstalling the qgrid2 labextension, I'm getting the following error when trying to execute qgrid.show_grid:

`AttributeError: module 'qgrid' has no attribute 'show_grid'`

Here is my conda environment for the relevant packages:

```
jupyter                   1.0.0                    py37_7  
jupyter_client            5.3.4                    py37_0  
jupyter_console           6.1.0                      py_0  
jupyter_core              4.6.1                    py37_0  
jupyterlab                2.1.5                    pypi_0    pypi
jupyterlab_server         1.1.5                      py_0  
nodejs                    10.13.0              he6710b0_0  
qgrid                     1.1.1                    py37_2  
```

Any advice?

**Comment by lebedov** [comment]
Not sure why you are experiencing import problems; `qgrid.show_grid` seems to exist in version 1.1.1. Alternately, try installing 1.3.1 from conda-forge.
